<?php

namespace Logevo\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SacRepository extends \Doctrine\ORM\EntityRepository
{
	private function getQueryBuilder()
	{
	    $em = $this->getEntityManager();
	 
	    $queryBuilder = $em->getRepository('LongevoModelBundle:Cliente')
	    ->createQueryBuilder('c')
	    ->leftJoin('LonjevoModelBundle:Pedido','p');
	 
	    return $queryBuilder;
	}

	public function findAllInOrder()
	{
	    exit('ok');
	    $qb = $this->getQueryBuilder()
	    ->orderBy('c.createdAt', 'desc');
	 
	    return $qb->getQuery()->getResult();
	}
}
